### ISSUE TITLE
Implement importance sampling for NoHit

### ISSUE THREAD

**Issue by nonl4331** [nonl4331/raytracing-rust#1]
**Description**
Currently, only Primitives are able to be importance sampled. Also being able to sample NoHit which often is a source of lighting would help scenes converge faster.

**Tasks**
- [x] Discrete 1D and 2D PDF sampling
- [x] Tests for 1D and 2D Sampling
- [x] Generate 2D (UV) PDF from Texture
- [x] Implementation for Sky<T>
- [x] Tests for NoHit sampling (for Sky<T>)
- [ ] MIS code

**Comment by nonl4331** [comment]
- [ ] Investigate #2
